import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube,} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/7529381-removebg-preview.png";

export default function Home(){
  return(
    <div>
      <Head>
        <title>Alisson Tomazelli Portfolio</title>
        <meta name="description" content="Generated by created" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12  flex justify-between ">
            <h1 className="text-xl">developedbyat</h1>
            <ul className="flex items-center">
              <li>
              < BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"  href="#aboutme">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-4xl py-2 text-teal-700 font-medium">Alisson Tomazelli</h2>
            <h3 className="text-2xl py-2">Developer and designer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Freelancer providing services for programming and design content needs. 
              Join me down below and let's get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-900 rounded-full w-60 h-60 ">
            <Image src={deved}/>
          </div>
        </section>
      </main>
    </div>
  )
}